//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.03 at 09:04:45 PM EDT 
//


package com.scrippsnetworks.wcm.export.snipage.xml.bind;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.scrippsnetworks.wcm.export.snipage.xml.bind package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.scrippsnetworks.wcm.export.snipage.xml.bind
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PVAL }
     * 
     */
    public PVAL createPVAL() {
        return new PVAL();
    }

    /**
     * Create an instance of {@link RECORD }
     * 
     */
    public RECORD createRECORD() {
        return new RECORD();
    }

    /**
     * Create an instance of {@link PROP }
     * 
     */
    public PROP createPROP() {
        return new PROP();
    }

    /**
     * Create an instance of {@link RECORDS }
     * 
     */
    public RECORDS createRECORDS() {
        return new RECORDS();
    }

}
